### ISSUE TITLE
ModuleNotFoundError: No module named 'com.aniket.dev.mrkt.analysis.tools'

### ISSUE THREAD

**Issue by modist** [aniket-work/Lets_Build_Market_Analysis_Team_w_AI_Agents#1]
I have been following the directions on a win 10 - but I get these errors :

2024-07-06 22:06:29.173 Uncaught app exception
Traceback (most recent call last):
  File "C:\Temp\Lets_Build_Market_Analysis_Team_w_AI_Agents\Lets_Build_Market_Analysis_Team_w_AI_Agents\Build_Market_Analysis_Team_w_AI_Agents\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Temp\Lets_Build_Market_Analysis_Team_w_AI_Agents\Lets_Build_Market_Analysis_Team_w_AI_Agents\main.py", line 5, in <module>
    from com.aniket.dev.mrkt.analysis.agents.market_observers import MarketObserverAgents
  File "C:\Temp\Lets_Build_Market_Analysis_Team_w_AI_Agents\Lets_Build_Market_Analysis_Team_w_AI_Agents\com\aniket\dev\mrkt\analysis\agents\market_observers.py", line 3, in <module>
    from com.aniket.dev.mrkt.analysis.tools.surfer_tool import SurferTool
ModuleNotFoundError: No module named 'com.aniket.dev.mrkt.analysis.tools'

**Comment by aniket-work** [comment]
Hey, Can you try now ( by taking latest) for some reason, tools didnt make it to push ( not sure if got git ignored) thanks for pointing it out

**Comment by modist** [comment]
thanks :-)

the interface starts now - but upen entering a companyname - I get this :
An error occurred: Error code: 404 - {'error': {'message': "model
'crewai-llama3-8b' not found, try pulling it first", 'type': 'api_error',
'param': None, 'code': None}}

**Comment by aniket-work** [comment]
Ah! you can use any other model, which you have in your ollama
